import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import classNames from "classnames";
import "@/globals.scss";

export const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={classNames(roboto.variable)}>
        {children}
      </body>
    </html>
  );
}
